import { NextResponse } from 'next/server';

type Airport = { iata_code: string; name: string; municipality: string; iso_country: string; aliases?: string[] };

const airports: Airport[] = [
  { iata_code: 'MCI', name: 'Kansas City International Airport', municipality: 'Kansas City', iso_country: 'US' },
  { iata_code: 'ATL', name: 'Hartsfield-Jackson Atlanta International Airport', municipality: 'Atlanta', iso_country: 'US' },
  { iata_code: 'BOS', name: 'Boston Logan International Airport', municipality: 'Boston', iso_country: 'US' },
  { iata_code: 'BWI', name: 'Baltimore/Washington International Airport', municipality: 'Baltimore', iso_country: 'US', aliases: ['Washington'] },
  { iata_code: 'CLT', name: 'Charlotte Douglas International Airport', municipality: 'Charlotte', iso_country: 'US' },
  { iata_code: 'DCA', name: 'Ronald Reagan Washington National Airport', municipality: 'Washington', iso_country: 'US', aliases: ['Washington DC', 'DC'] },
  { iata_code: 'DEN', name: 'Denver International Airport', municipality: 'Denver', iso_country: 'US' },
  { iata_code: 'DFW', name: 'Dallas/Fort Worth International Airport', municipality: 'Dallas', iso_country: 'US', aliases: ['Fort Worth'] },
  { iata_code: 'DTW', name: 'Detroit Metropolitan Wayne County Airport', municipality: 'Detroit', iso_country: 'US' },
  { iata_code: 'EWR', name: 'Newark Liberty International Airport', municipality: 'Newark', iso_country: 'US', aliases: ['New York'] },
  { iata_code: 'FLL', name: 'Fort Lauderdale-Hollywood International Airport', municipality: 'Fort Lauderdale', iso_country: 'US', aliases: ['Miami'] },
  { iata_code: 'IAH', name: 'George Bush Intercontinental Airport', municipality: 'Houston', iso_country: 'US' },
  { iata_code: 'JFK', name: 'John F. Kennedy International Airport', municipality: 'New York', iso_country: 'US' },
  { iata_code: 'LAX', name: 'Los Angeles International Airport', municipality: 'Los Angeles', iso_country: 'US' },
  { iata_code: 'LAS', name: 'Harry Reid International Airport', municipality: 'Las Vegas', iso_country: 'US' },
  { iata_code: 'LGA', name: 'LaGuardia Airport', municipality: 'New York', iso_country: 'US' },
  { iata_code: 'MCO', name: 'Orlando International Airport', municipality: 'Orlando', iso_country: 'US' },
  { iata_code: 'MIA', name: 'Miami International Airport', municipality: 'Miami', iso_country: 'US' },
  { iata_code: 'MSP', name: 'Minneapolis-Saint Paul International Airport', municipality: 'Minneapolis', iso_country: 'US', aliases: ['St Paul', 'Saint Paul'] },
  { iata_code: 'ORD', name: "Chicago O'Hare International Airport", municipality: 'Chicago', iso_country: 'US' },
  { iata_code: 'PHL', name: 'Philadelphia International Airport', municipality: 'Philadelphia', iso_country: 'US' },
  { iata_code: 'PHX', name: 'Phoenix Sky Harbor International Airport', municipality: 'Phoenix', iso_country: 'US' },
  { iata_code: 'SAN', name: 'San Diego International Airport', municipality: 'San Diego', iso_country: 'US' },
  { iata_code: 'SEA', name: 'Seattle-Tacoma International Airport', municipality: 'Seattle', iso_country: 'US' },
  { iata_code: 'SFO', name: 'San Francisco International Airport', municipality: 'San Francisco', iso_country: 'US' },
  { iata_code: 'SLC', name: 'Salt Lake City International Airport', municipality: 'Salt Lake City', iso_country: 'US' },
  { iata_code: 'STL', name: 'St. Louis Lambert International Airport', municipality: 'St. Louis', iso_country: 'US' },
  { iata_code: 'TPA', name: 'Tampa International Airport', municipality: 'Tampa', iso_country: 'US' },
  { iata_code: 'YYZ', name: 'Toronto Pearson International Airport', municipality: 'Toronto', iso_country: 'CA' },
  { iata_code: 'YVR', name: 'Vancouver International Airport', municipality: 'Vancouver', iso_country: 'CA' },
  { iata_code: 'YUL', name: 'Montréal-Trudeau International Airport', municipality: 'Montreal', iso_country: 'CA' },
  { iata_code: 'AMS', name: 'Amsterdam Airport Schiphol', municipality: 'Amsterdam', iso_country: 'NL' },
  { iata_code: 'ATH', name: 'Athens International Airport', municipality: 'Athens', iso_country: 'GR' },
  { iata_code: 'BCN', name: 'Barcelona-El Prat Airport', municipality: 'Barcelona', iso_country: 'ES' },
  { iata_code: 'BER', name: 'Berlin Brandenburg Airport', municipality: 'Berlin', iso_country: 'DE' },
  { iata_code: 'BRU', name: 'Brussels Airport', municipality: 'Brussels', iso_country: 'BE' },
  { iata_code: 'CDG', name: 'Paris Charles de Gaulle Airport', municipality: 'Paris', iso_country: 'FR' },
  { iata_code: 'CPH', name: 'Copenhagen Airport', municipality: 'Copenhagen', iso_country: 'DK' },
  { iata_code: 'DUB', name: 'Dublin Airport', municipality: 'Dublin', iso_country: 'IE' },
  { iata_code: 'FCO', name: 'Leonardo da Vinci-Fiumicino Airport', municipality: 'Rome', iso_country: 'IT' },
  { iata_code: 'FRA', name: 'Frankfurt Airport', municipality: 'Frankfurt', iso_country: 'DE' },
  { iata_code: 'GVA', name: 'Geneva Airport', municipality: 'Geneva', iso_country: 'CH' },
  { iata_code: 'LHR', name: 'London Heathrow Airport', municipality: 'London', iso_country: 'GB' },
  { iata_code: 'LGW', name: 'London Gatwick Airport', municipality: 'London', iso_country: 'GB' },
  { iata_code: 'STN', name: 'London Stansted Airport', municipality: 'London', iso_country: 'GB' },
  { iata_code: 'LTN', name: 'London Luton Airport', municipality: 'London', iso_country: 'GB' },
  { iata_code: 'LCY', name: 'London City Airport', municipality: 'London', iso_country: 'GB' },
  { iata_code: 'LIS', name: 'Humberto Delgado Airport', municipality: 'Lisbon', iso_country: 'PT' },
  { iata_code: 'MAD', name: 'Adolfo Suárez Madrid-Barajas Airport', municipality: 'Madrid', iso_country: 'ES' },
  { iata_code: 'MXP', name: 'Milan Malpensa Airport', municipality: 'Milan', iso_country: 'IT' },
  { iata_code: 'LIN', name: 'Milan Linate Airport', municipality: 'Milan', iso_country: 'IT' },
  { iata_code: 'MUC', name: 'Munich Airport', municipality: 'Munich', iso_country: 'DE' },
  { iata_code: 'PRG', name: 'Václav Havel Airport Prague', municipality: 'Prague', iso_country: 'CZ' },
  { iata_code: 'VIE', name: 'Vienna International Airport', municipality: 'Vienna', iso_country: 'AT' },
  { iata_code: 'ZRH', name: 'Zurich Airport', municipality: 'Zurich', iso_country: 'CH' },
  { iata_code: 'BUD', name: 'Budapest Ferenc Liszt International Airport', municipality: 'Budapest', iso_country: 'HU' },
  { iata_code: 'ZAG', name: 'Franjo Tuđman Airport', municipality: 'Zagreb', iso_country: 'HR' },
  { iata_code: 'VCE', name: 'Venice Marco Polo Airport', municipality: 'Venice', iso_country: 'IT' },
  { iata_code: 'NCE', name: 'Nice Côte d’Azur Airport', municipality: 'Nice', iso_country: 'FR' },
  { iata_code: 'IST', name: 'Istanbul Airport', municipality: 'Istanbul', iso_country: 'TR' },
  { iata_code: 'NRT', name: 'Narita International Airport', municipality: 'Tokyo', iso_country: 'JP' },
  { iata_code: 'HND', name: 'Haneda Airport', municipality: 'Tokyo', iso_country: 'JP' },
  { iata_code: 'ICN', name: 'Incheon International Airport', municipality: 'Seoul', iso_country: 'KR' },
  { iata_code: 'GMP', name: 'Gimpo International Airport', municipality: 'Seoul', iso_country: 'KR' },
  { iata_code: 'PEK', name: 'Beijing Capital International Airport', municipality: 'Beijing', iso_country: 'CN' },
  { iata_code: 'PKX', name: 'Beijing Daxing International Airport', municipality: 'Beijing', iso_country: 'CN' },
  { iata_code: 'PVG', name: 'Shanghai Pudong International Airport', municipality: 'Shanghai', iso_country: 'CN' },
  { iata_code: 'HKG', name: 'Hong Kong International Airport', municipality: 'Hong Kong', iso_country: 'HK' },
  { iata_code: 'SIN', name: 'Singapore Changi Airport', municipality: 'Singapore', iso_country: 'SG' },
  { iata_code: 'BKK', name: 'Suvarnabhumi Airport', municipality: 'Bangkok', iso_country: 'TH' },
  { iata_code: 'DEL', name: 'Indira Gandhi International Airport', municipality: 'Delhi', iso_country: 'IN' },
  { iata_code: 'BOM', name: 'Chhatrapati Shivaji Maharaj International Airport', municipality: 'Mumbai', iso_country: 'IN' },
  { iata_code: 'DXB', name: 'Dubai International Airport', municipality: 'Dubai', iso_country: 'AE' },
  { iata_code: 'DOH', name: 'Hamad International Airport', municipality: 'Doha', iso_country: 'QA' },
  { iata_code: 'JNB', name: 'O. R. Tambo International Airport', municipality: 'Johannesburg', iso_country: 'ZA' },
  { iata_code: 'CPT', name: 'Cape Town International Airport', municipality: 'Cape Town', iso_country: 'ZA' },
  { iata_code: 'GRU', name: 'São Paulo-Guarulhos International Airport', municipality: 'São Paulo', iso_country: 'BR' },
  { iata_code: 'EZE', name: 'Ezeiza International Airport', municipality: 'Buenos Aires', iso_country: 'AR' },
  { iata_code: 'SCL', name: 'Arturo Merino Benítez International Airport', municipality: 'Santiago', iso_country: 'CL' },
  { iata_code: 'MEX', name: 'Mexico City International Airport', municipality: 'Mexico City', iso_country: 'MX' },
  { iata_code: 'CUN', name: 'Cancún International Airport', municipality: 'Cancún', iso_country: 'MX' },
  { iata_code: 'SYD', name: 'Sydney Kingsford Smith Airport', municipality: 'Sydney', iso_country: 'AU' },
  { iata_code: 'MEL', name: 'Melbourne Airport', municipality: 'Melbourne', iso_country: 'AU' },
  { iata_code: 'AKL', name: 'Auckland Airport', municipality: 'Auckland', iso_country: 'NZ' },
];

export async function GET(request: Request) {
  const query = new URL(request.url).searchParams.get('q')?.trim().toLowerCase() ?? '';
  if (query.length < 2) return NextResponse.json({ airports: [] });

  const matches = airports
    .filter((airport) => [airport.iata_code, airport.name, airport.municipality, ...(airport.aliases ?? [])].some((value) => value.toLowerCase().includes(query)))
    .filter((airport, index, list) => list.findIndex((item) => item.iata_code === airport.iata_code) === index)
    .slice(0, 8);

  return NextResponse.json({ airports: matches });
}
