import { redirect } from 'next/navigation';
import Link from 'next/link';
import SiteHeader from '@/components/site-header';
import { getDb, ensureSchema } from '@/lib/db';
import { requireAdmin, isAdminError } from '@/lib/admin';
import AdminAlertActions from './admin-alert-actions';
import styles from './admin.module.css';

export const dynamic = 'force-dynamic';

function formatDate(value: string | Date | null) { if (!value) return 'Never'; return new Date(value).toLocaleString(); }
function formatCriteria(criteria: Record<string, unknown>) { const origin = String(criteria.origin ?? '?'); const destination = String(criteria.destination ?? 'Anywhere'); const cabin = criteria.cabin === 'premium_economy' ? 'Premium economy' : criteria.cabin === 'business' ? 'Business' : criteria.cabin === 'first' ? 'First' : 'Economy'; return `${origin} → ${destination} · ${cabin} · $${Number(criteria.maxPrice ?? 0).toLocaleString()}`; }
function pct(value: number, total: number) { return total ? `${Math.round((value / total) * 100)}%` : '0%'; }
function barWidth(value: number, max: number) { return `${max ? Math.max(3, Math.round((value / max) * 100)) : 0}%`; }

export default async function AdminPage() {
  try {
    await ensureSchema(); const admin = await requireAdmin(); const db = getDb();
    const [userCounts, alertCounts, signalCounts, runCounts, recentUsers, recentAlerts, recentRuns, recentAudit, dailyUsers, dailyRuns, frequencies, cabins, destinations, affiliateStats, affiliateProviders] = await Promise.all([
      db.query<{ total: string; free: string; pro: string; last_7d: string; last_30d: string }>(`select count(*)::text as total, count(*) filter (where plan = 'free')::text as free, count(*) filter (where plan <> 'free' or subscription_status in ('active','trialing','lifetime'))::text as pro, count(*) filter (where created_at >= now() - interval '7 days')::text as last_7d, count(*) filter (where created_at >= now() - interval '30 days')::text as last_30d from users`),
      db.query<{ total: string; active: string; due: string; daily: string; weekly: string; monthly: string }>(`select count(*)::text as total, count(*) filter (where active)::text as active, count(*) filter (where active and (last_checked_at is null or (frequency = 'Daily' and last_checked_at <= now() - interval '24 hours') or (frequency = 'Weekly' and last_checked_at <= now() - interval '7 days') or (frequency = 'Monthly' and last_checked_at <= now() - interval '30 days')))::text as due, count(*) filter (where frequency = 'Daily')::text as daily, count(*) filter (where frequency = 'Weekly')::text as weekly, count(*) filter (where frequency = 'Monthly')::text as monthly from alerts`),
      db.query<{ total: string; last_24h: string; last_7d: string; last_30d: string }>(`select count(*)::text as total, count(*) filter (where sent_at >= now() - interval '24 hours')::text as last_24h, count(*) filter (where sent_at >= now() - interval '7 days')::text as last_7d, count(*) filter (where sent_at >= now() - interval '30 days')::text as last_30d from signals`),
      db.query<{ total: string; errors: string; success: string; running: string; last_24h: string; offers: string; emailed: string }>(`select count(*)::text as total, count(*) filter (where status = 'error')::text as errors, count(*) filter (where status = 'success')::text as success, count(*) filter (where status = 'running')::text as running, count(*) filter (where started_at >= now() - interval '24 hours')::text as last_24h, coalesce(sum(offers_found),0)::text as offers, count(*) filter (where email_sent)::text as emailed from alert_runs`),
      db.query<{ id: string; email: string; name: string | null; plan: string; subscription_status: string; created_at: string }>(`select id, email, name, plan, subscription_status, created_at from users order by created_at desc limit 12`),
      db.query<{ id: string; email: string; criteria: Record<string, unknown>; frequency: string; active: boolean; last_checked_at: string | null; created_at: string }>(`select a.id, a.email, a.criteria, a.frequency, a.active, a.last_checked_at, a.created_at from alerts a order by a.created_at desc limit 20`),
      db.query<{ id: string; alert_id: string; status: string; started_at: string; finished_at: string | null; offers_found: number; email_sent: boolean; error_message: string | null; email: string }>(`select r.id, r.alert_id, r.status, r.started_at, r.finished_at, r.offers_found, r.email_sent, r.error_message, a.email from alert_runs r join alerts a on a.id = r.alert_id order by r.started_at desc limit 20`),
      db.query<{ id: string; admin_email: string; action: string; target_type: string | null; target_id: string | null; created_at: string }>(`select id, admin_email, action, target_type, target_id, created_at from admin_audit_log order by created_at desc limit 15`),
      db.query<{ day: string; users: string; alerts: string }>(`select to_char(d.day, 'MM/DD') as day, (select count(*) from users u where u.created_at >= d.day and u.created_at < d.day + interval '1 day')::text as users, (select count(*) from alerts a where a.created_at >= d.day and a.created_at < d.day + interval '1 day')::text as alerts from generate_series(current_date - interval '13 days', current_date, interval '1 day') d(day) order by d.day`),
      db.query<{ day: string; runs: string; errors: string; offers: string; emails: string }>(`select to_char(d.day, 'MM/DD') as day, (select count(*) from alert_runs r where r.started_at >= d.day and r.started_at < d.day + interval '1 day')::text as runs, (select count(*) from alert_runs r where r.started_at >= d.day and r.started_at < d.day + interval '1 day' and r.status = 'error')::text as errors, (select coalesce(sum(r.offers_found),0) from alert_runs r where r.started_at >= d.day and r.started_at < d.day + interval '1 day')::text as offers, (select count(*) from alert_runs r where r.started_at >= d.day and r.started_at < d.day + interval '1 day' and r.email_sent) ::text as emails from generate_series(current_date - interval '13 days', current_date, interval '1 day') d(day) order by d.day`),
      db.query<{ frequency: string; count: string }>(`select coalesce(frequency,'Unknown') frequency, count(*)::text count from alerts group by frequency order by count(*) desc`),
      db.query<{ cabin: string; count: string }>(`select coalesce(criteria->>'cabin','unknown') cabin, count(*)::text count from alerts group by cabin order by count(*) desc`),
      db.query<{ destination: string; count: string }>(`select coalesce(criteria->>'destination', criteria->>'destinationAirport', 'Anywhere') destination, count(*)::text count from alerts group by destination order by count(*) desc limit 12`),
      db.query<{ vertical: string; clicks: string; users: string; last_7d: string; last_30d: string }>(`select vertical, count(*)::text clicks, count(distinct user_id)::text users, count(*) filter (where clicked_at >= now() - interval '7 days')::text last_7d, count(*) filter (where clicked_at >= now() - interval '30 days')::text last_30d from affiliate_clicks group by vertical order by count(*) desc`),
      db.query<{ provider: string; clicks: string }>(`select provider, count(*)::text clicks from affiliate_clicks group by provider order by count(*) desc limit 12`),
    ]);
    const u = userCounts.rows[0], a = alertCounts.rows[0], s = signalCounts.rows[0], r = runCounts.rows[0];
    const totalRuns = Number(r?.total ?? 0), successRuns = Number(r?.success ?? 0), errorRuns = Number(r?.errors ?? 0);
    const maxDailyUsers = Math.max(1, ...dailyUsers.rows.map((x) => Number(x.users)));
    const maxDailyRuns = Math.max(1, ...dailyRuns.rows.map((x) => Number(x.runs)));
    const maxDestination = Math.max(1, ...destinations.rows.map((x) => Number(x.count)));
    const maxAffiliate = Math.max(1, ...affiliateStats.rows.map((x) => Number(x.clicks)));
    const maxProvider = Math.max(1, ...affiliateProviders.rows.map((x) => Number(x.clicks)));

    return <main className={styles.page}><SiteHeader authenticated /><section className="shell"><div className={styles.main}>
      <div className={styles.masthead}><div><p className={styles.eyebrow}>TripSignal administration</p><h1 className={styles.title}>Operations</h1><p className={styles.subhead}>Signed in as {admin.email}</p></div><div><Link className="button button-secondary" href="/admin/health">System health</Link><span className={styles.adminBadge}>ADMIN</span></div></div>

      <section className={styles.grid}><div className={styles.metric}><span>Users</span><strong>{u?.total ?? 0}</strong><small>{u?.last_7d ?? 0} in 7 days · {u?.last_30d ?? 0} in 30 days</small></div><div className={styles.metric}><span>Pro users</span><strong>{u?.pro ?? 0}</strong><small>{u?.free ?? 0} free accounts</small></div><div className={styles.metric}><span>Active alerts</span><strong>{a?.active ?? 0}</strong><small>{a?.due ?? 0} currently due</small></div><div className={styles.metric}><span>Fare signals</span><strong>{s?.last_30d ?? 0}</strong><small>{s?.total ?? 0} all time</small></div><div className={styles.metric}><span>Search runs</span><strong>{r?.last_24h ?? 0}</strong><small>{r?.errors ?? 0} errors all time</small></div></section>

      <section className={styles.analyticsSection}><div className={styles.sectionHeading}><div><p className={styles.eyebrow}>Telemetry</p><h2>Live system profile</h2></div><span className={styles.sectionNote}>QUERY WINDOW · 14D / ALL TIME</span></div>
        <div className={styles.analyticsGrid}>
          <div className={styles.analyticsCard}><div className={styles.cardLabel}>RUN SUCCESS RATE</div><strong>{pct(successRuns, totalRuns)}</strong><div className={styles.progress}><i style={{ width: pct(successRuns, totalRuns) }} /></div><div className={styles.cardMeta}><span>{successRuns.toLocaleString()} successful</span><span>{errorRuns.toLocaleString()} failed</span></div></div>
          <div className={styles.analyticsCard}><div className={styles.cardLabel}>OFFER YIELD</div><strong>{totalRuns ? (Number(r?.offers ?? 0) / totalRuns).toFixed(2) : '0.00'}</strong><div className={styles.microBars}>{dailyRuns.rows.map((x) => <i key={x.day} style={{ height: `${Math.max(5, (Number(x.offers) / Math.max(1, ...dailyRuns.rows.map((d) => Number(d.offers)))) * 100)}%` }} title={`${x.day}: ${x.offers} offers`} />)}</div><div className={styles.cardMeta}><span>{Number(r?.offers ?? 0).toLocaleString()} offers</span><span>all runs</span></div></div>
          <div className={styles.analyticsCard}><div className={styles.cardLabel}>EMAIL DELIVERY</div><strong>{pct(Number(r?.emailed ?? 0), totalRuns)}</strong><div className={styles.progress}><i style={{ width: pct(Number(r?.emailed ?? 0), totalRuns) }} /></div><div className={styles.cardMeta}><span>{r?.emailed ?? 0} run emails</span><span>{s?.last_24h ?? 0} signals / 24h</span></div></div>
          <div className={styles.analyticsCard}><div className={styles.cardLabel}>ALERT DENSITY</div><strong>{a?.total ?? 0}</strong><div className={styles.density}><i style={{ width: barWidth(Number(a?.active ?? 0), Number(a?.total ?? 0)) }} /></div><div className={styles.cardMeta}><span>{a?.active ?? 0} active</span><span>{a?.due ?? 0} due</span></div></div>
        </div>
      </section>

      <section className={styles.analyticsSection}><div className={styles.sectionHeading}><div><p className={styles.eyebrow}>Activity matrix</p><h2>14-day acquisition & worker load</h2></div><span className={styles.sectionNote}>DAILY AGGREGATES</span></div>
        <div className={styles.matrix}><div className={styles.matrixHeader}><span>DATE</span><span>NEW USERS</span><span>ALERTS CREATED</span><span>SEARCH RUNS</span><span>FAILURES</span><span>OFFERS</span></div>{dailyUsers.rows.map((day, index) => { const runDay = dailyRuns.rows[index]; return <div className={styles.matrixRow} key={day.day}><span>{day.day}</span><span><b>{day.users}</b><i style={{ width: barWidth(Number(day.users), maxDailyUsers) }} /></span><span>{day.alerts}</span><span><b>{runDay?.runs ?? 0}</b><i style={{ width: barWidth(Number(runDay?.runs ?? 0), maxDailyRuns) }} /></span><span className={Number(runDay?.errors ?? 0) ? styles.error : ''}>{runDay?.errors ?? 0}</span><span>{runDay?.offers ?? 0}</span></div>; })}</div>
      </section>

      <section className={styles.analyticsSection}><div className={styles.sectionHeading}><div><p className={styles.eyebrow}>Demand intelligence</p><h2>What users are asking TripSignal to find</h2></div><span className={styles.sectionNote}>{a?.total ?? 0} ALERT DEFINITIONS</span></div>
        <div className={styles.demandGrid}>
          <div className={styles.analyticsCard}><div className={styles.cardLabel}>SCAN FREQUENCY</div>{frequencies.rows.map((item) => <div className={styles.rankRow} key={item.frequency}><span>{item.frequency}</span><b>{item.count}</b><i style={{ width: barWidth(Number(item.count), Number(a?.total ?? 0)) }} /></div>)}</div>
          <div className={styles.analyticsCard}><div className={styles.cardLabel}>CABIN MIX</div>{cabins.rows.map((item) => <div className={styles.rankRow} key={item.cabin}><span>{item.cabin.replace('_', ' ')}</span><b>{item.count}</b><i style={{ width: barWidth(Number(item.count), Number(a?.total ?? 0)) }} /></div>)}</div>
          <div className={styles.analyticsCard}><div className={styles.cardLabel}>TOP DESTINATIONS</div>{destinations.rows.map((item) => <div className={styles.rankRow} key={item.destination}><span>{item.destination}</span><b>{item.count}</b><i style={{ width: barWidth(Number(item.count), maxDestination) }} /></div>)}</div>
        </div>
      </section>

      <section className={styles.analyticsSection}><div className={styles.sectionHeading}><div><p className={styles.eyebrow}>Affiliate telemetry</p><h2>Trip intent after the fare search</h2></div><span className={styles.sectionNote}>REAL CLICK DATA · NO REVENUE ASSUMPTIONS</span></div>
        <div className={styles.demandGrid}>
          <div className={styles.analyticsCard}><div className={styles.cardLabel}>CLICKS BY VERTICAL</div>{affiliateStats.rows.length ? affiliateStats.rows.map((item) => <div className={styles.rankRow} key={item.vertical}><span>{item.vertical}</span><b>{item.clicks}</b><i style={{ width: barWidth(Number(item.clicks), maxAffiliate) }} /><small>{item.last_7d} / 7D</small></div>) : <div className={styles.empty}>No affiliate clicks recorded yet.</div>}</div>
          <div className={styles.analyticsCard}><div className={styles.cardLabel}>PROVIDER SHARE</div>{affiliateProviders.rows.length ? affiliateProviders.rows.map((item) => <div className={styles.rankRow} key={item.provider}><span>{item.provider}</span><b>{item.clicks}</b><i style={{ width: barWidth(Number(item.clicks), maxProvider) }} /></div>) : <div className={styles.empty}>No provider click data yet.</div>}</div>
          <div className={styles.analyticsCard}><div className={styles.cardLabel}>MONETIZATION SURFACE</div><strong>{affiliateStats.rows.reduce((sum, item) => sum + Number(item.clicks), 0).toLocaleString()}</strong><div className={styles.cardMeta}><span>tracked outbound clicks</span><span>7D / 30D available above</span></div><div className={styles.signalCode}>AFFILIATE_EVENTS / CLICKSTREAM / LIVE</div></div>
        </div>
      </section>

      <section className={styles.section}><div className={styles.sectionHeading}><div><p className={styles.eyebrow}>Users</p><h2>Recent accounts</h2></div><span className={styles.sectionNote}>Showing {recentUsers.rows.length}</span></div><div className={styles.table}><div className={styles.tableHead}><span>Account</span><span>Plan</span><span>Status</span><span>Created</span></div>{recentUsers.rows.map((user) => <Link href={`/admin/users/${user.id}`} className={styles.tableRowLink} key={user.id}><div className={styles.tableRow}><div><strong>{user.name || user.email.split('@')[0]}</strong><small>{user.email}</small></div><span>{user.plan === 'free' ? 'Free' : 'Pro'}</span><span>{user.subscription_status}</span><span>{formatDate(user.created_at)}</span></div></Link>)}</div></section>
      <section className={styles.section}><div className={styles.sectionHeading}><div><p className={styles.eyebrow}>Alerts</p><h2>Active monitoring</h2></div><span className={styles.sectionNote}>{a?.total ?? 0} total · {a?.due ?? 0} due</span></div><div className={styles.table}><div className={styles.tableHead}><span>Alert</span><span>Frequency</span><span>Last checked</span><span>Action</span></div>{recentAlerts.rows.map((alert) => <Link href={`/admin/alerts/${alert.id}`} className={styles.tableRowLink} key={alert.id}><div className={styles.tableRow}><div><strong>{formatCriteria(alert.criteria)}</strong><small>{alert.email}</small></div><span>{alert.frequency}</span><span>{formatDate(alert.last_checked_at)}</span><span><AdminAlertActions id={alert.id} active={alert.active} /></span></div></Link>)}</div></section>
      <section className={styles.section}><div className={styles.sectionHeading}><div><p className={styles.eyebrow}>System health</p><h2>Recent search runs</h2></div><span className={styles.sectionNote}>{r?.errors ?? 0} errors recorded</span></div><div className={styles.table}><div className={styles.tableHead}><span>Account</span><span>Result</span><span>Started</span><span>Details</span></div>{recentRuns.rows.map((run) => <div className={styles.tableRow} key={run.id}><div><strong>{run.email}</strong><small>{run.alert_id}</small></div><span className={run.status === 'error' ? styles.error : run.status === 'success' ? styles.success : ''}>{run.status}</span><span>{formatDate(run.started_at)}</span><span>{run.status === 'error' ? (run.error_message || 'Unknown error') : `${run.offers_found} offers${run.email_sent ? ' · email sent' : ''}`}</span></div>)}{!recentRuns.rows.length && <div className={styles.empty}>No alert runs recorded yet.</div>}</div></section>
      <section className={styles.section}><div className={styles.sectionHeading}><div><p className={styles.eyebrow}>Audit log</p><h2>Admin actions</h2></div></div><div className={styles.table}>{recentAudit.rows.map((entry) => <div className={styles.auditRow} key={entry.id}><span>{formatDate(entry.created_at)}</span><strong>{entry.action}</strong><span>{entry.target_type ? `${entry.target_type} ${entry.target_id || ''}` : ''}</span><span>{entry.admin_email}</span></div>)}{!recentAudit.rows.length && <div className={styles.empty}>No admin actions recorded yet.</div>}</div></section>
    </div></section></main>;
  } catch (error) { if (isAdminError(error)) redirect('/signin'); throw error; }
}
